namespace SpriteKind {
    export const pawn = SpriteKind.create()
    export const king = SpriteKind.create()
    export const queen = SpriteKind.create()
    export const bishop = SpriteKind.create()
    export const knight = SpriteKind.create()
    export const rook = SpriteKind.create()
}
let b_king_1 = sprites.create(assets.image`b_k`, SpriteKind.king)
b_king_1.setPosition(68, 7)
let w_king_2 = sprites.create(assets.image`w_k`, SpriteKind.king)
w_king_2.setPosition(68, 112)
let b_queen_1 = sprites.create(assets.image`b_q`, SpriteKind.queen)
b_queen_1.setPosition(53, 7)
let w_queen_2 = sprites.create(assets.image`w_q`, SpriteKind.queen)
w_queen_2.setPosition(53, 112)
let b_bishop_2 = sprites.create(assets.image`b_b`, SpriteKind.bishop)
b_bishop_2.setPosition(37, 7)
let b_bishop_1 = sprites.create(assets.image`b_b`, SpriteKind.bishop)
b_bishop_1.setPosition(83, 7)
let w_bishop_2 = sprites.create(assets.image`w_b`, SpriteKind.bishop)
w_bishop_2.setPosition(37, 112)
let w_bishop_1 = sprites.create(assets.image`w_b`, SpriteKind.bishop)
w_bishop_1.setPosition(83, 112)
let b_knight_2 = sprites.create(assets.image`b_n`, SpriteKind.knight)
b_knight_2.setPosition(98, 7)
let b_knight_1 = sprites.create(assets.image`b_n`, SpriteKind.knight)
b_knight_1.setPosition(23, 7)
let w_knight_2 = sprites.create(assets.image`w_n`, SpriteKind.knight)
w_knight_2.setPosition(98, 112)
let w_knight_1 = sprites.create(assets.image`w_n`, SpriteKind.knight)
w_knight_1.setPosition(23, 112)
let b_rook_2 = sprites.create(assets.image`b_r`, SpriteKind.rook)
b_rook_2.setPosition(7, 7)
let b_rook_1 = sprites.create(assets.image`b_r`, SpriteKind.rook)
b_rook_1.setPosition(113, 7)
let w_rook_2 = sprites.create(assets.image`w_r`, SpriteKind.rook)
w_rook_2.setPosition(113, 112)
let w_rook_1 = sprites.create(assets.image`w_r`, SpriteKind.rook)
w_rook_1.setPosition(7, 112)
let b_pawn_8 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_7 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_6 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_5 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_4 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_3 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_2 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_1 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let w_pawn_8 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_7 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_6 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_5 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_4 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_2 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_1 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
scene.setBackgroundImage(assets.image`board`)
