namespace SpriteKind {
    export const pawn = SpriteKind.create()
    export const king = SpriteKind.create()
    export const queen = SpriteKind.create()
    export const bishop = SpriteKind.create()
    export const knight = SpriteKind.create()
    export const rook = SpriteKind.create()
}
let b_king_1 = sprites.create(assets.image`b_k`, SpriteKind.king)
b_king_1.setPosition(68, 7)
let w_king_2 = sprites.create(assets.image`w_k`, SpriteKind.king)
w_king_2.setPosition(68, 112)
let b_queen_1 = sprites.create(assets.image`b_q`, SpriteKind.queen)
b_queen_1.setPosition(53, 7)
let w_queen_2 = sprites.create(assets.image`w_q`, SpriteKind.queen)
w_queen_2.setPosition(53, 112)
let b_bishop_2 = sprites.create(assets.image`b_b`, SpriteKind.bishop)
let b_bishop_1 = sprites.create(assets.image`b_b`, SpriteKind.bishop)
let w_bishop_2 = sprites.create(assets.image`w_b`, SpriteKind.bishop)
let w_bishop_1 = sprites.create(assets.image`w_b`, SpriteKind.bishop)
let b_knight_2 = sprites.create(assets.image`b_n`, SpriteKind.knight)
let b_knight_1 = sprites.create(assets.image`b_n`, SpriteKind.knight)
let w_knight_2 = sprites.create(assets.image`w_n`, SpriteKind.knight)
let w_knight_1 = sprites.create(assets.image`w_n`, SpriteKind.knight)
let b_rook_2 = sprites.create(assets.image`b_r`, SpriteKind.rook)
let b_rook_1 = sprites.create(assets.image`b_r`, SpriteKind.rook)
let w_rook_2 = sprites.create(assets.image`w_r`, SpriteKind.rook)
let w_rook_1 = sprites.create(assets.image`w_r`, SpriteKind.rook)
let b_pawn_8 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_7 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_6 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_5 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_4 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_3 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_2 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let b_pawn_1 = sprites.create(assets.image`b_p`, SpriteKind.pawn)
let w_pawn_8 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_7 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_6 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_5 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_4 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_2 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
let w_pawn_1 = sprites.create(assets.image`w_p`, SpriteKind.pawn)
scene.setBackgroundImage(assets.image`board`)
